### ISSUE TITLE
Connection timeout issue

### ISSUE THREAD

**Issue by szymonszrajer** [loosolab/TOBIAS_snakemake#13]
Im trying out the TOBIAS_snakemake pipeline on a few samples and Im getting a connection timeout error. Is there a way to run the  pipeline on a cluster without external network connection?

[config.txt](https://github.com/loosolab/TOBIAS_snakemake/files/14769599/config.txt)
 
[connection_timeout.txt](https://github.com/loosolab/TOBIAS_snakemake/files/14769601/connection_timeout.txt)

**Comment by mohobein** [comment]
Hey @szymonszrajer, 

thank your for using the TOBIAS snakemake pipeline. The error stems from the attempt to download and deploy the Wilson app for interactive omics visualization. This cannot be done without a connection to the internet.

If this Wilson visualization is not important to you, the easiest solution for your problem would be disabling that part of the pipeline. You can do that by adjusting the config file under flags. Set `wilson: False`.

Otherwise, we need to think about it further. I am not sure if there is a way to deploy the web app under your given circumstances. One option without adjustments to the pipeline would be to deploy Wilson with the output files of the analysis manually on a machine with an external network connection after the pipeline finished.

I hope this helps.

Best regards,
Moritz

**Comment by szymonszrajer** [comment]
Hi thank you for the response. I was under the impression that its possible to create a TOBIAS environment (tobias_snakemake_env) once and run the pipeline by calling Snakemake inside the environment. However, when I changed the wilson flag to False Im getting errors regarding conda now - issues during retrieving dependencies (I cannot connect to the conda channels from the node I am running TOBIAS_snakemake on).

Does conda need to retrieve dependencies each time the pipeline is ran or does the test run on data-tobias-2020 create all of the environments once? If the environments are only created once I could perform the test run on a node that can access the conda channels. The problem with that is that I would need to find a way to obtain the test data in some way other than running the command `TOBIAS DownloadData`.

Thank you for the help.

**Comment by mohobein** [comment]
The environment tobias_snakemake_env that you created during the pipeline setup is an environment to run snakemake itself, not to run the tools that are used during the pipeline. For them, snakemake creates individual environments as specified by the other `environments/*.yaml` files. These will be reused after you ran the pipeline once if the yaml files were not changed since last time.

Performing the test run on a node with access to conda should fix your problem.

If you are having trouble retrieving the test data without internet access on your node, subsetting your own files (i.e. to contain one chromosome only) for a quick pipeline run to build the environments might be a solution.

Let me know if this resolved your issue!

**Comment by szymonszrajer** [comment]
Most of the environments could be made on the other node but the test run failed to make the last two. I ended up using classic TOBIAS. Thank you for the help!

**Comment by mohobein** [comment]
Alright, that is unfortunate, but at least your were able to find a workaround for your analysis. Thank you for reporting back!
